Content/urls.py
from django.contrib import admin
from django.urls import path,include

#Start My imports static files 
from django.conf import settings
from django.conf.urls.static import static
#End my static files imports
from . import views

from django.contrib.sitemaps.views import sitemap
from .sitemaps import AppSitemap

sitemaps = {
    
    "posts": AppSitemap,
}


urlpatterns = [
    #Create Update Watch and Delete Video
    path('contents/sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("contents/sitemap-posts.xml", sitemap, {"sitemaps": {"posts": AppSitemap}}, name="django.contrib.sitemaps.views.sitemap"),
    #
    path('<slug:order_id>',views.PostDetailView_one.as_view(),name='post_detail'),
    path('<str:username>/web/application/<slug:order_id>/', views.PostDetailView.as_view(), name='post'),
]

Feed/urls.py
from django.contrib import admin
from django.urls import path,include

#Start My imports static files 
from django.conf import settings
from django.conf.urls.static import static
#End my static files imports

from . import views



urlpatterns = [
    path('', views.cornical_feed.as_view(), name='feed'),
]

htmx_urlpatterns = [
    
]

urlpatterns += htmx_urlpatterns

Plural/urls.py
from django.contrib import admin
from django.urls import path,include

#Start My imports static files 
from django.conf import settings
from django.conf.urls.static import static
#End my static files imports
admin.site.site_header = "Plural"
admin.site.site_title = "Plural"
admin.site.index_title = "Darshboard Portal"

urlpatterns = [
    path('00-0-00/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('Content.urls')),
    path('', include('Main.urls')),
    path('', include('Startqt.urls')),
    path('', include('Profile.urls')),
    path('', include('Feed.urls')),
    path('', include('Discover.urls')),
    path('', include('Setting.urls')),
    path('', include('Graph.urls')),
    path('', include('Document.urls')),
    path('', include('Search.urls')),
    path('accounts/', include('allauth.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Content/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from Graph.models import Topic
from .namingr import get_app_icon_path, get_app_thumbnail_path, get_appcarousel_media_path
import uuid
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
from django.utils.crypto import get_random_string


class App(models.Model):
    order_id = models.CharField(max_length=120, unique=True, blank=True)
    short_code = models.CharField(max_length=10, unique=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150, blank=True, null=True)
    description = models.TextField(max_length=5000, blank=True, null=True)
    icon = models.ImageField(upload_to=get_app_icon_path, max_length=5000, blank=True,
                              default="default/app/icon/icon.png")
    thumbnail = models.ImageField(upload_to=get_app_thumbnail_path, max_length=5000, blank=True,
                                   default="default/app/thumbnail/thumbnail.png")
    url = models.URLField(max_length=250, blank=True)
    color = models.CharField(max_length=150, blank=True, default="#2a6602")
    background_color = models.CharField(max_length=150, blank=True, default="#ccedab")
    category = models.ForeignKey(Topic, related_name="app_category", on_delete=models.SET_NULL, null=True, blank=True)
    views = models.ManyToManyField(User, related_name="app_views", blank=True)
    views_counter = models.IntegerField(default=0)
    pinned = models.BooleanField(default=False)
    edited = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.order_id:
            base_order_id = slugify(self.name)
            self.order_id = f"{base_order_id}-{self.created_at.strftime('%Y-%m-%d-%H-%M-%S')}"
        if not self.short_code:
            self.short_code = get_random_string(length=10)
        super().save(*args, **kwargs)

    def total_views(self):
        return self.views.count()

    def is_popular(self):
        return self.views_counter > 100

    def get_absolute_url(self):
        return reverse('app_detail', kwargs={'order_id': self.order_id})

    def __str__(self):
        return f'{self.user.username}::{self.name}'

    class Meta:
        ordering = ['-created_at']


@receiver(pre_save, sender=App)
def set_post_like_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())


class AppCarousel(models.Model):
    app = models.ForeignKey(App, default=None, on_delete=models.CASCADE)
    media = models.ImageField(upload_to=get_appcarousel_media_path, max_length=5000, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.app.name}'

Content/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from Content.models import App
from django.core.exceptions import ValidationError
from ckeditor.fields import RichTextField
from ckeditor.widgets import CKEditorWidget


class CommentBForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.TextInput(attrs={'class':'uk-input uk-width-1-1    uk-form-small uk-text-meta brt rounded-sm ','placeholder':'Add Comment'}),label=False)

    class Meta:
        model = App
        fields = ['comment']





#Contents Categories
VideoCategory_list = (
  ("Film & Animation", "Film & Animation"),
  ("Autos & Vehicles", "Autos & Vehicles"),
  ("Music", "Music"),
  ("Pets & Animals", "Pets & Animals"),
  ("Sports", "Sports"),
  ("Travel & Events", "Travel & Events"),
  ("Gaming", "Gaming"),
  ("People & Blogs", "People & Blogs"),
  ("Comedy", "Comedy"),
  ("Entertainment", "Entertainment"),
  ("News & Politics", "News & Politics"),
  ("Howto & Style ", "Howto & Style"),
  ("Education", "Education"),
  ("Science & Technology", "Science & Technology"),
  ("Nonprofits & Activism", "Nonprofits & Activism"),
  )


class AppForm(forms.ModelForm):
    description = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...'
            }))

    image = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'multiple': True
            })
    )

    class Meta:
        model = App
        fields = ['description']


#Getting Username and Password{"C = as Capital letter"}
#======================================================
class CreateAppForm(ModelForm):
    title = forms.CharField(widget=forms.Textarea(attrs={'class':'uk-input bg-pH','placeholder':'Add title'}),label=False)
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'uk-textarea bg-pH','rows':'7','placeholder':'Add description'}),label=False)
    media = forms.ImageField(widget=forms.FileInput(attrs={'accept':'image/*','capture':'user','class':'uk-input bg-secondary','placeholder':'Thumbnail'}),label=False, required=False)
    tags = forms.CharField()

    class Meta:
      model = App
      fields = ['title','description', 'media', 'tags']

Content/views.py
from django.shortcuts import render,HttpResponse,redirect, get_object_or_404
from Graph.models import Topic
from django.contrib import messages
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django import forms
from django.http import HttpResponseRedirect, HttpResponse
import json
from django.http import JsonResponse
from .forms import *
import random
import time
from django.views import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_GET
from django.views.generic import FormView
from django.forms import modelformset_factory

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from PIL import Image
import uuid




@require_GET
def robots_txt(request):
    lines = [
        # Group 1 - General
        "User-Agent: * ",
        "Allow: /genre/",
        "Allow: /read/",
        "Allow: /collection/",
        "Disallow: /cntnts/",

        # Group 1 - Google
        "User-Agent: Googlebot",
        "Allow: /genre/",
        "Allow: /read/",
        "Allow: /collection/",
        "Disallow: /cntnts/",

        # Group 1 - Yandex
        "User-Agent: Yandexbot",
        "Allow: /genre/",
        "Allow: /read/",
        "Allow: /collection/",
        "Disallow: /cntnts/",
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")

discover_randow_colors =[
{
    'color': '#003dff'
},
{
    'color':'#7e9e00'
},
{
    'color':'#ffa600'
},
{
    'color':'#c9a45d'
}
]

class PostDetailView(View):
    def get(self, request, username, order_id, *args, **kwargs):
        user = request.user
        post = App.objects.get(user__username=username, order_id=order_id)
        qs = json.dumps(list(App.objects.values()) ,default=str)
        color = random.choices(discover_randow_colors, k=1)
        
        context = {
            'post': post,
            'color':color,
        }
        return render(request, 'Content/Detail/post_detail.html', context)



class PostDetailView_one(View):
    def get(self, request, order_id, *args, **kwargs):
        user = request.user
        post = App.objects.get(order_id=order_id)
        qs = json.dumps(list(App.objects.values()) ,default=str)
        color = random.choices(discover_randow_colors, k=1)

        context = {
            'post': post,
            'color':color,
        }

        return render(request, 'Content/Detail/post_detail.html', context)

Content/templates/Content/Detail/post_detail.html
{% extends 'Main/Base/base.html' %}

{% block title %} 

{{ post.name }}


{% endblock %}

{% block content %}
{% load static %}

<div>
  
  <div class="uk-grid">
    <div class="uk-width-1-6">

       <div class="embed-video embed-item rounded-xlg iq-border uk-background-cover" data-src="{{ post.icon.url}}" uk-img="" style="background-image: url(&quot;{{ post.icon.url}}&quot;);" >

                    
                    <span class="broadcast_content_icon_list uk-flex uk-flex-middle">

                    </span>
                    </div>
      
    </div>

    <div class="uk-width-expand">

      <p class="text-black uk-text-xlarge">{{post.name}}</p>
      <p class=" text-grey uk-text-xlarge">{{post.category}}</p>
      <p>
        <a href="{{ post.url }}" class="button circle primary">Launch application</a>
      </p>
      
    </div>

  </div>


  <section class="">
    <div class="uk-padding-small ">
    <p class=" text-black uk-text-bold">{{ post.description }}</p>
     </div>
  </section>

  <section class="">

    <div class="bg-pH rounded iq-border uk-height-medium uk-padding-small uk-flex uk-flex-middle">

      <div class="uk-width-1-1">

      <div class="uk-position-relative uk-slider" uk-slider="finite: true">

                    <div class="uk-slider-container pb-3">

                        <ul class="uk-slider-items uk-child-width-1-3@m uk-child-width-1-3@s uk-grid-small uk-grid" uk-scrollspy="target: > div; cls: uk-animation-slide-bottom-small; delay: 100" style="transform: translate3d(-203px, 0px, 0px);">

                            <li tabindex="-1" class="">
                                <div class="game-card">
                                    <!-- Group Card Thumbnail -->
                                    <div class="game-card-thumbnail">
                                        <img src="{{ post.thumbnail.url}}" alt="">
                                    </div>
                                </div>

                            </li> 

                            {% if post.appcarousel_set.exists %}

                            {% for carousel_item in post.appcarousel_set.all %}

                            <li tabindex="-1" class="">
                                <div class="game-card">
                                    <!-- Group Card Thumbnail -->
                                    <div class="game-card-thumbnail">
                                        <img src="{{ carousel_item.media.url }}" alt="">
                                    </div>
                                </div>

                            </li> 

                            {% endfor %}
                            {% endif %}
                            
                        </ul>

                        <a class="uk-position-center-left-out uk-position-small uk-hidden-hover slidenav-prev" href="#" uk-slider-item="previous"></a>
                        <a class="uk-position-center-right-out uk-position-small uk-hidden-hover slidenav-next uk-invisible" href="#" uk-slider-item="next"></a>

                    </div>


                </div>
              </div>
      
    </div>
  </section>

</div>

{% endblock %}